### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by xiaowenkaihun** [mklissa/MOC#2]
I read your paper and am very interested，I have finished setting up the environment, and now I need to render its running process. I don’t know how to complete it. I am a freshman and my code knowledge is not very good. Can the author help me solve it?

**Comment by mklissa** [comment]
Hello @xiaowenkaihun, I'd be happy to help you out. What experiments are you trying to render? If it's the deep RL ones, you would wrap the environment inside `gym.wrappers.Monitor` and then use `env.render` in the main loop. To see which option is being used, I would simply use `print(option)` in the main loop once again. There are other ways to overlay the current option on the rendering by digging up the mujoco code, but its a bit more work. Let me know how it goes.

**Comment by xiaowenkaihun** [comment]
I'm glad you took the time to answer my questions, I need to use the mujoco simulator to render the antwalk experiment, and I want to print the reward curve as shown in your paper, how can I do it? There is also the third miniword experiment. I encountered the following error when running it. I did not solve it. How can I solve the problem?

Traceback (most recent call last):
  File "run.py", line 193, in get_alg_module
    alg_module = import_module('.'.join(['baselines', alg, submodule]))
  File "/home/lab1207/anaconda3/envs/miniworld/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lab1207/wenyijun/miniworld/baselines/ppo2_options/ppo2_options.py", line 13, in <module>
    from baselines.ppo2_options_new.runner import Runner
ModuleNotFoundError: No module named 'baselines.ppo2_options_new'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 312, in <module>
    main(sys.argv)
  File "run.py", line 250, in main
    model, env = train(args, extra_args)
  File "run.py", line 65, in train
    learn = get_learn_function(args.alg)
  File "run.py", line 202, in get_learn_function
    return get_alg_module(alg).learn
  File "run.py", line 196, in get_alg_module
    alg_module = import_module('.'.join(['rl_' + 'algs', alg, submodule]))
  File "/home/lab1207/anaconda3/envs/miniworld/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rl_algs'

**Comment by mklissa** [comment]
Hello, very sorry for the late reply, I have been quite busy with some deadlines. For the error on the MiniWorld experiment, I have updated the file that should hopefully fix it, let me know if it does. Thanks for sharing that error. For the plotting on the Ant experiment, there are different ways to do it, it really depends on what you prefer to use for plotting. The experiment results should be already saving through the logger (i.e. https://github.com/mklissa/MOC/blob/main/continuous_control/baselines/ppoc_int/pposgd_simple.py#L485). You could then use https://github.com/mklissa/MOC/blob/main/continuous_control/baselines/results_plotter.py to plot the results. Hopefully this helps.
